spring:
  data:
    mongodb:
      uri: mongodb+srv://${DB_USER:admin}:${DB_PASSWORD:spring-webflux}@springwebfluxcluster.kfsszxk.mongodb.net/${DB_NAME}?retryWrites=true&w=majority&appName=SpringWebfluxCluster