spring:
  data:
    mongodb:
      uri: mongodb+srv://${DB_USER:admin}:${DB_PASSWORD}@springwebfluxcluster.kfsszxk.mongodb.net/${DB_NAME:spring-webflux}?retryWrites=true&w=majority&appName=SpringWebfluxCluster
      auto-index-creation: true
  application:
    name: spring-webflux